---
- hosts: 10.142.0.6
  vars:
    nexus_version: latest-unix
    nexus_download_url: https://download.sonatype.com/nexus/3/{{nexus_version}}.tar.gz
    nexus_download_dest: /tmp/nexus-{{nexus_version}}.tar.gz
    nexus_extracted_dir: /tmp/nexus_extracted_dir
    nexus_dir: /usr/local/nexus

  become: true
  tasks:
  - name: install wget
    yum:
      name: wget
      state: present

  - name: install openjdk
    yum:
      name: java-1.8.0-openjdk
      state: present

  - name: install unzip
    yum:
      name: unzip
      state: present

  - name: create nexus group
    group: 
      name: nexus
    sudo: true

  - name: create nexus user
    user: 
      name: nexus 
      group: nexus
    sudo: true

  - name: download nexus
    get_url: 
      url: "{{nexus_download_url}}"
      dest: "{{nexus_download_dest}}"
    register: nexus_download

  - name: create {{nexus_extracted_dir}} directory
    file: 
      path: "{{nexus_extracted_dir}}" 
      state: directory
    when: nexus_download.changed
    sudo: true

  - name: extract nexus to {{nexus_extracted_dir}}
    unarchive:
      src: "{{nexus_download_dest}}"
      dest: "{{nexus_extracted_dir}}"
      remote_src: true
    when: nexus_download.changed
    sudo: true

  - name: move nexus to {{nexus_dir}} directory
    command: cp -a {{nexus_extracted_dir}}/. {{nexus_dir}}
    when: nexus_download.changed
    sudo: true

  - name: remove {{nexus_extracted_dir}} directory
    command: rm -rf {{nexus_extracted_dir}}
    when: nexus_download.changed
    sudo: true

  - name: make {{nexus_dir}} directory property of nexus user/group
    file: 
      path: "{{nexus_dir}}" 
      group: nexus 
      owner: nexus 
      recurse: true
    sudo: true

  - name: run nexus as nexus user
    lineinfile: 
      dest: "{{nexus_dir}}/nexus-3.14.0-04/bin/nexus" 
      regexp: "#RUN_AS_USER=" 
      line: "RUN_AS_USER=nexus" 
      backrefs: true
    sudo: true

  - name: set NEXUS_HOME
    lineinfile: 
      dest: "{{nexus_dir}}/nexus-3.14.0-04/bin/nexus" 
      regexp: "^NEXUS_HOME" 
      line: "NEXUS_HOME={{nexus_dir}}" 
      backrefs: true
    sudo: true

  - name: create nexus piddir
    file: 
      path: /var/run/nexus 
      state: directory 
      group: nexus 
      owner: nexus
    sudo: true

  - name: set nexus piddir
    lineinfile: 
      dest: "{{nexus_dir}}/nexus-3.14.0-04/bin/nexus" 
      regexp: "^#PIDDIR=" 
      line: "PIDDIR=/var/run/nexus" 
      backrefs: true
    sudo: true

  - name: create symbolic links to /etc/init.d/nexus
    file: 
      src: "{{nexus_dir}}/nexus-3.14.0-04/bin/nexus" 
      dest: /etc/init.d/nexus 
      state: link
    sudo: true

  - name: configure runlevel links for nexus
    command: chkconfig --add nexus 
    sudo: true

  - name: configure nexus levels
    command: chkconfig --levels 345 nexus on
    sudo: true

  - name: set nexus working directory
    lineinfile: 
      dest: "{{nexus_dir}}/nexus-3.14.0-04/etc/nexus-default.properties" 
      regexp: "^nexus-work=" 
      line: "nexus-work=${bundleBasedir}/work/nexus"
    sudo: true

  - name: start nexus
    service: 
      name: nexus 
      state: restarted 
      pattern: "{{nexus_dir}}/nexus-3.14.0-04"
    sudo: true
...

